[package]
name = "yamato-core"
description = "Fan curves, profiles and the control engine"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
yamato-ec = { path = "../yamato-ec" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
